language: node_js
sudo: true
node_js:
- '7'
before_install:
- openssl aes-256-cbc -K $encrypted_460c0dacd794_key -iv $encrypted_460c0dacd794_iv
  -in service-account.json.enc -out service-account.json -d
script: "./build.sh"
after_failure:
- cat firebase-debug.log
- cat firestore-debug.log